export const marqueeContent = {
  options: [
    "WEDDINGS · PRIVATE EVENTS · CORPORATE CELEBRATIONS · VENUE EXPERIENCES · EVENT PRODUCTION · FURNITURE RENTAL · LOGISTICS · MONTRÉAL",
    "CREATE · PRODUCE · CELEBRATE · CONNECT · TRANSFORM · GATHER · REMEMBER",
    "EVENTOS QUE CONECTAN · EXPERIENCIAS QUE PERMANECEN · ESPACIOS QUE COBRAN VIDA",
  ],
} as const;
